spring.application.name=portfolio-back

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thiagocarrizoham@gmail.com
spring.mail.password=hnozquciohvcjahk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
